# Use postgres/example user/password credentials
version: "3.9"

services:
  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    volumes:
      - postgres:/dev/shm
    ports:
      - ${HOST_PG_PORT}:5432
    environment:
      POSTGRES_PASSWORD: ${PG_PASS}

  adminer:
    image: adminer
    restart: always
    ports:
      - ${HOST_ADMINER_PORT}:8080

volumes:
  postgres:
